### ISSUE TITLE
Version v1.0.3 crashes

### ISSUE THREAD

**Issue by EvaMart** [inab/github-metadata-api#2]
App crashes because of some problem with `../VERSION` route.

**Comment by EvaMart** [comment]
The error: 

```
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '../VERSION'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.<anonymous> (/Users/evabsc/projects/software-observatory/github-metadata-api/src/swaggerDefinition.js:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/evabsc/projects/software-observatory/github-metadata-api/src/index.js:22:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '../VERSION'
}
```
